services:
  ai-app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    environment:
      - OPENROUTER_API_KEY
      - BASE_URL
      - MODEL_NAME
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
